[project]
name = "vinted-mocked-apis"
version = "0.1.0"
description = ""
authors = ["DMA <digital-marketing-automation@vinted.com>"]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
